<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { useSessionStore } from '@/stores/session'
import { useSettingsStore } from '@/stores/settings'

const route = useRoute()
const session = useSessionStore()
const settings = useSettingsStore()

const titles = computed<Record<string, [string, string]>>(() => ({
  practice: ['Practice', session.cat.name],
  result: ['Result', session.cat.name],
  coach: ['Coach', 'Auto-generated by skill level'],
  library: ['Library', 'Custom texts and cloud library'],
  dict: ['Dictionary', 'Drill any entry directly'],
  ai: ['AI', 'Auto title, category and difficulty'],
  models: ['Local models', 'Tokenizer, embedding and rerank models'],
  stats: ['Stats', 'Last 30 days'],
  leaderboard: ['Progress', session.period === 'daily' ? 'This week vs last' : 'This month vs last'],
  settings: ['Settings', 'Preferences and achievements'],
}))

const current = computed(() => titles.value[String(route.name || 'practice')] || titles.value.practice)
</script>

<template>
  <div class="topbar">
    <div class="titles">
      <span class="title">{{ current[0] }}</span>
      <span class="sub">{{ current[1] }}</span>
    </div>
    <div class="meta">
      <span class="net" @click="settings.toggleOnline()">
        <a-badge
          :status="settings.offline ? 'warning' : 'success'"
          :text="settings.offline ? 'Offline · 3 pending' : 'Synced 2 min ago'"
        />
      </span>
      <span class="hint">Ctrl+Enter Start · Ctrl+N Next text</span>
      <span class="user">chen.wei</span>
    </div>
  </div>
</template>

<style scoped>
.topbar {
  height: 48px;
  background: var(--surface);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.03);
  flex-shrink: 0;
}
.titles { display: flex; align-items: baseline; gap: 12px; }
.title { font-size: 14px; font-weight: 600; }
.sub { font-size: 14px; color: var(--text-3); }
.meta { display: flex; align-items: center; gap: 12px; }
.net { cursor: pointer; white-space: nowrap; }
.hint { font-size: 12px; color: var(--text-3); white-space: nowrap; }
.user { font-size: 14px; color: var(--text-2); }
</style>
